webempresa/blog/urls.py
from django.urls import path
from . import views
from blog import views as blog_views # Importa de nuestra app core 

urlpatterns = [
    path('', blog_views.blog, name="blog"),
    path('category/<int:category_id>/', blog_views.category, name="category"),

]

webempresa/services/services/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

webempresa/webempresa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    # Paths del core
    path('', include('core.urls')),
    # Paths del services
    path('services/', include('services.urls')),
    # Paths del blog
    path('blog/', include('blog.urls')),
    # Paths del pages
    path('page/', include('pages.urls')),
    # Paths del contact
    path('contact/', include('contact.urls')),
    # Paths del admin
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

webempresa/pages/models.py
from django.db import models

from ckeditor.fields import RichTextField

# Create your models here.
class Page(models.Model):
    title = models.CharField(max_length=200,verbose_name="Título")
    #content = models.TextField(verbose_name="Contenido")
    content = RichTextField(verbose_name="Contenido")
    order = models.SmallIntegerField(verbose_name="Orden",default=0)
    # Estos dos como son automaticos al final
    activo = models.BooleanField(default=True, verbose_name="¿Activo?")  # ✅ Nuevo campo booleano
    created = models.DateTimeField(auto_now_add=True,verbose_name="Fecha de Creación")
    updated = models.DateTimeField(auto_now=True,verbose_name="Fecha de Actualización")

    class Meta:
        verbose_name='pagina'
        verbose_name_plural='paginas'
        ordering = ["order","-title"]
        
    def __str__(self):
        return self.title     

webempresa/pages/templates/pages/sample.html
{% extends 'core/base.html'%}

{% load static %}  <!-- Asegúrate de colocar 'load static' aquí, no dentro de bloques -->

{% block title %}Contacto{%endblock%} 

{% block content %}

    <section class="page-section about-heading">
      <div class="container">
        <div class="about-heading-content mbtm">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5 forced">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-lower">{{page.title}}</span>
                </h2>
                <div class="section-content">
                  {{page.content|safe}}
                  {% if user.is_authenticated %} <!-- este lo dejo para ver que se puede preguntar asi pero sobra-->
                    {% if perms.pages.change_page %}
                      <a href="{% url 'admin:pages_page_change' page.id %}" target="_blank">Editar ...</a>
                    {% endif%}
                  {% endif%}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{%endblock%} 